name: upload

env:
  module: app
  buildpath: build/outputs
  basename: foobar

on:

  push:
    branches: [ "main" ]
  #workflow_run:
  #  workflows: [ "build" ]
  #  branches: [ "master" ]
  #  types:
  #    - completed
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: gradlew exec
        run: chmod +x gradlew
      - name: assemble release apk
        run: ./gradlew assembleRelease
      - name: bundle release
        run: ./gradlew bundleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.basename }} - apk
          path: ${{ env.module }}/${{ env.buildpath }}/apk/release/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.basename }} - abb
          path: ${{ env.module }}/${{ env.buildpath }}/bundle/release/
      # only tagged commits
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.module }}/${{ env.buildpath }}/apk/release/*.apk
            ${{ env.module }}/${{ env.buildpath }}/bundle/release/*.aab